version: '2.1'
services:
  app:
    restart: always
    build:
      context: .
      args:
        dev: "true"
    ports:
      - "127.0.0.1:8022:3000"
#     - "3000:3000"
    env_file:
     - .env
    # command: ["npm", "start"]
    # volumes:
    #  - .:/home/node
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    restart: always
    ports:
     - 127.0.0.1:27017:27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo 127.0.0.1/test --quiet"]
      interval: 2s
      timeout: 10s
      retries: 3
    volumes:
      - db:/data/db
      - lib:/var/lib/mongodb
      - log:/var/log/mongodb

volumes:
    db:
    lib:
    log:
